// <auto-generated />
using System;
using GaHealthcareNurses.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GaHealthcareNurses.DbMigration.Migrations
{
    [DbContext(typeof(GaHealthcareNursesContext))]
    [Migration("20210210064832_AddedServiceListTable")]
    partial class AddedServiceListTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("GaHealthcareNurses.Entity.Models.CareCoordinationNote", b =>
                {
                    b.Property<int>("CareCoordinationNoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("Aide")
                        .HasColumnType("bit");

                    b.Property<bool>("CaseManager")
                        .HasColumnType("bit");

                    b.Property<bool>("CommunityResource")
                        .HasColumnType("bit");

                    b.Property<string>("Discussion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DmeVendor")
                        .HasColumnType("bit");

                    b.Property<bool>("Don")
                        .HasColumnType("bit");

                    b.Property<int?>("JobId")
                        .HasColumnType("int");

                    b.Property<bool>("MSW")
                        .HasColumnType("bit");

                    b.Property<bool>("OT_COTA")
                        .HasColumnType("bit");

                    b.Property<bool>("Other")
                        .HasColumnType("bit");

                    b.Property<bool>("PT_PTA")
                        .HasColumnType("bit");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int");

                    b.Property<bool>("Pharmacist")
                        .HasColumnType("bit");

                    b.Property<bool>("Physician")
                        .HasColumnType("bit");

                    b.Property<bool>("RN_LPN_LVN")
                        .HasColumnType("bit");

                    b.Property<string>("Resolution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SLP")
                        .HasColumnType("bit");

                    b.Property<bool>("TherapySupervisor")
                        .HasColumnType("bit");

                    b.HasKey("CareCoordinationNoteId");

                    b.HasIndex("PatientId");

                    b.ToTable("CareCoordinationNote");
                });

            modelBuilder.Entity("GaHealthcareNurses.Entity.Models.CareRecipient", b =>
                {
                    b.Property<int>("CareRecipientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("CareRecipientLocationId")
                        .HasColumnType("int");

                    b.Property<int?>("CareRecipientRelationshipId")
                        .HasColumnType("int");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("ClientId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Frequency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FunctionalLimitation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GenderPreference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleInitial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoteToCaregiver")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Receptiveness")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StateId")
                        .HasColumnType("int");

                    b.Property<string>("WhenToStart")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CareRecipientId");

                    b.HasIndex("CareRecipientLocationId");

                    b.HasIndex("CareRecipientRelationshipId");

                    b.HasIndex("CityId");

                    b.HasIndex("ClientId");

                    b.HasIndex("StateId");

                    b.ToTable("CareRecipient");
                });

            modelBuilder.Entity("GaHealthcareNurses.Entity.Models.CareRecipientLocation", b =>
                {
                    b.Property<int>("CareRecipientLocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CurrentLocation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CareRecipientLocationId");

                    b.ToTable("CareRecipientLocation");
                });

            modelBuilder.Entity("GaHealthcareNurses.Entity.Models.CareRecipientRelationship", b =>
                {
                    b.Property<int>("CareRecipientRelationshipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Relationship")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CareRecipientRelationshipId");

                    b.ToTable("CareRecipientRelationship");
                });

            modelBuilder.Entity("GaHealthcareNurses.Entity.Models.Certification", b =>
                {
                    b.Property<int>("CertificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("AdditionInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CertificationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CertificationState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CertificationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfExpiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("NurseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("StateId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CertificationId");

                    b.HasIndex("NurseId");

                    b.HasIndex("StateId");

                    b.ToTable("Certification");
                });

            modelBuilder.Entity("GaHealthcareNurses.Entity.Models.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.Property<int>("ZipCode")
                        .HasColumnType("int");

                    b.HasKey("CityId");

                    b.HasIndex("StateId");

                    b.ToTable("City");
                });

            modelBuilder.Entity("GaHealthcareNurses.Entity.Models.Client", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AddressLine1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BestTimeToCal")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CareRecipientRelationshipId")
                        .HasColumnType("int");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Designation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HowYouHeardAboutUs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleInitial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferralName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CareRecipientRelationshipId");

                    b.HasIndex("CityId");

                    b.HasIndex("StateId");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("GaHealthcareNurses.Entity.Models.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Abbreviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("GaHealthcareNurses.Entity.Models.Education", b =>
                {
                    b.Property<int>("EducationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime?>("AttendedFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AttendedTo")
                        .HasColumnType("datetime2");

                    b.Property<string>("CompleteAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EducationTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Institution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Major")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NurseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OtherQualification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecializedTraining")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EducationId");

                    b.HasIndex("EducationTypeId");

                    b.HasIndex("NurseId");

                    b.ToTable("Education");
                });

            modelBuilder.Entity("GaHealthcareNurses.Entity.Models.EducationType", b =>
                {
                    b.Property<int>("EducationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EducationTypeId");

                    b.ToTable("EducationType");
                });

            modelBuilder.Entity("GaHealthcareNurses.Entity.Models.Employer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AddressLine1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StateId")
                        .HasColumnType("int");

                    b.Property<string>("TelephoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employer");
                });

            modelBuilder.Entity("GaHealthcareNurses.Entity.Models.HiringAgreements", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("AbuseNeglectAndExploitationPolicy")
                        .HasColumnType("bit");

                    b.Property<bool>("AcknowledgementOfPoliciesAndProcedures")
                        .HasColumnType("bit");

                    b.Property<bool>("ClientCareInEmergency")
                        .HasColumnType("bit");

                    b.Property<bool>("CodeOfEthics")
                        .HasColumnType("bit");

                    b.Property<bool>("ConfidientiallyStatement")
                        .HasColumnType("bit");

                    b.Property<bool>("CredibleEvidenceOfAbuseStatement")
                        .HasColumnType("bit");

                    b.Property<bool>("DeclinationOfInfluenzaVaccination")
                        .HasColumnType("bit");

                    b.Property<bool>("FireOrSafetyProcedure")
                        .HasColumnType("bit");

                    b.Property<bool>("GahRegulations")
                        .HasColumnType("bit");

                    b.Property<bool>("JobDescription")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("HiringAgreements");
                });

            modelBuilder.Entity("GaHealthcareNurses.Entity.Models.Job", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JobId");

                    b.HasIndex("EmployerId");

                    b.ToTable("Job");
                });

            modelBuilder.Entity("GaHealthcareNurses.Entity.Models.Nurse", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AddressLine1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Availability")
                        .HasColumnType("bit");

                    b.Property<string>("AvailableToWork")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<bool>("ContactPresentEmployer")
                        .HasColumnType("bit");

                    b.Property<string>("ContactTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CriminalActivity")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DateAvailableToWork")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyContactAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyContactPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyContactRelationship")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HoursPerWeek")
                        .HasColumnType("int");

                    b.Property<bool>("IneligibleForParticipation")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LawfullyBecomingEmployed")
                        .HasColumnType("bit");

                    b.Property<string>("MiddleInitial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfliePicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonForIneligible")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonForWork")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocialSecurityNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StateId")
                        .HasColumnType("int");

                    b.Property<string>("StepsInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelephoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Trasnportation")
                        .HasColumnType("bit");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("Nurse");
                });

            modelBuilder.Entity("GaHealthcareNurses.Entity.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("AddressLine1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Alert")
                        .HasColumnType("bit");

                    b.Property<string>("Allergies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("CodeStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Forgetful")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StateId")
                        .HasColumnType("int");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PatientId");

                    b.ToTable("Patient");
                });

            modelBuilder.Entity("GaHealthcareNurses.Entity.Models.Reference", b =>
                {
                    b.Property<int>("ReferenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NurseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Occupation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReferenceId");

                    b.HasIndex("NurseId");

                    b.ToTable("Reference");
                });

            modelBuilder.Entity("GaHealthcareNurses.Entity.Models.RequiredService", b =>
                {
                    b.Property<int>("RequiredServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClientId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ServiceListId")
                        .HasColumnType("int");

                    b.HasKey("RequiredServiceId");

                    b.HasIndex("ClientId");

                    b.HasIndex("ServiceListId");

                    b.ToTable("RequiredService");
                });

            modelBuilder.Entity("GaHealthcareNurses.Entity.Models.ServiceList", b =>
                {
                    b.Property<int>("ServiceListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ServiceListId");

                    b.ToTable("ServiceList");
                });

            modelBuilder.Entity("GaHealthcareNurses.Entity.Models.State", b =>
                {
                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StateId");

                    b.HasIndex("CountryId");

                    b.ToTable("State");
                });

            modelBuilder.Entity("GaHealthcareNurses.Entity.Models.TaskList", b =>
                {
                    b.Property<int>("TaskListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("BloodPressureNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBloodPressureChecked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPainRatingChecked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPulseChecked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTemperatureChecked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWeightChecked")
                        .HasColumnType("bit");

                    b.Property<string>("PainRatingNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PulseNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemperatureNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VisitNoteId")
                        .HasColumnType("int");

                    b.Property<string>("WeightNotes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TaskListId");

                    b.HasIndex("VisitNoteId");

                    b.ToTable("TaskList");
                });

            modelBuilder.Entity("GaHealthcareNurses.Entity.Models.UploadDocuments", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CnaOrProfessionalLicense")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CprProvideNewLicense")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DrivingLicense")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EVerifyWillPulled")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HiringDisclosures")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HiringPreScreening")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfficeWillPulled")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PcaTest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SexOffenderReportOfficeWillPulled")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ssn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffPortalInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TbTestResults")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("GaHealthcareNurses.Entity.Models.VisitNote", b =>
                {
                    b.Property<int>("VisitNoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("BillingCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CheckBloodPressure")
                        .HasColumnType("bit");

                    b.Property<bool>("CheckPainRating")
                        .HasColumnType("bit");

                    b.Property<bool>("CheckTemperature")
                        .HasColumnType("bit");

                    b.Property<bool>("CheckWeight")
                        .HasColumnType("bit");

                    b.Property<string>("EmployerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("NurseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TimeIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TimeOut")
                        .HasColumnType("datetime2");

                    b.HasKey("VisitNoteId");

                    b.HasIndex("EmployerId");

                    b.HasIndex("JobId");

                    b.HasIndex("NurseId");

                    b.HasIndex("PatientId");

                    b.ToTable("VisitNote");
                });

            modelBuilder.Entity("GaHealthcareNurses.Entity.Models.WorkExperience", b =>
                {
                    b.Property<int>("WorkExperienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Employer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HourlyRate")
                        .HasColumnType("int");

                    b.Property<bool>("IsContactAllowed")
                        .HasColumnType("bit");

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameOfSupervisor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NurseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonForLeaving")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("YourDuties")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WorkExperienceId");

                    b.HasIndex("NurseId");

                    b.ToTable("WorkExperience");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("GaHealthcareNurses.Entity.Models.CareCoordinationNote", b =>
                {
                    b.HasOne("GaHealthcareNurses.Entity.Models.Patient", "Patient")
                        .WithMany("CareCoordinationNotes")
                        .HasForeignKey("PatientId");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("GaHealthcareNurses.Entity.Models.CareRecipient", b =>
                {
                    b.HasOne("GaHealthcareNurses.Entity.Models.CareRecipientLocation", "CareRecipientLocation")
                        .WithMany("CareRecipients")
                        .HasForeignKey("CareRecipientLocationId");

                    b.HasOne("GaHealthcareNurses.Entity.Models.CareRecipientRelationship", "CareRecipientRelationship")
                        .WithMany("CareRecipients")
                        .HasForeignKey("CareRecipientRelationshipId");

                    b.HasOne("GaHealthcareNurses.Entity.Models.City", "City")
                        .WithMany("CareRecipients")
                        .HasForeignKey("CityId");

                    b.HasOne("GaHealthcareNurses.Entity.Models.Client", "Client")
                        .WithMany("CareRecipients")
                        .HasForeignKey("ClientId");

                    b.HasOne("GaHealthcareNurses.Entity.Models.State", "State")
                        .WithMany("CareRecipients")
                        .HasForeignKey("StateId");

                    b.Navigation("CareRecipientLocation");

                    b.Navigation("CareRecipientRelationship");

                    b.Navigation("City");

                    b.Navigation("Client");

                    b.Navigation("State");
                });

            modelBuilder.Entity("GaHealthcareNurses.Entity.Models.Certification", b =>
                {
                    b.HasOne("GaHealthcareNurses.Entity.Models.Nurse", "Nurse")
                        .WithMany("Certifications")
                        .HasForeignKey("NurseId");

                    b.HasOne("GaHealthcareNurses.Entity.Models.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId");

                    b.Navigation("Nurse");

                    b.Navigation("State");
                });

            modelBuilder.Entity("GaHealthcareNurses.Entity.Models.City", b =>
                {
                    b.HasOne("GaHealthcareNurses.Entity.Models.State", "State")
                        .WithMany("Cities")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("GaHealthcareNurses.Entity.Models.Client", b =>
                {
                    b.HasOne("GaHealthcareNurses.Entity.Models.CareRecipientRelationship", "CareRecipientRelationship")
                        .WithMany("Clients")
                        .HasForeignKey("CareRecipientRelationshipId");

                    b.HasOne("GaHealthcareNurses.Entity.Models.City", "City")
                        .WithMany("Clients")
                        .HasForeignKey("CityId");

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GaHealthcareNurses.Entity.Models.State", "State")
                        .WithMany("Clients")
                        .HasForeignKey("StateId");

                    b.Navigation("CareRecipientRelationship");

                    b.Navigation("City");

                    b.Navigation("IdentityUser");

                    b.Navigation("State");
                });

            modelBuilder.Entity("GaHealthcareNurses.Entity.Models.Education", b =>
                {
                    b.HasOne("GaHealthcareNurses.Entity.Models.EducationType", "EducationType")
                        .WithMany("Education")
                        .HasForeignKey("EducationTypeId");

                    b.HasOne("GaHealthcareNurses.Entity.Models.Nurse", "Nurse")
                        .WithMany("Educations")
                        .HasForeignKey("NurseId");

                    b.Navigation("EducationType");

                    b.Navigation("Nurse");
                });

            modelBuilder.Entity("GaHealthcareNurses.Entity.Models.HiringAgreements", b =>
                {
                    b.HasOne("GaHealthcareNurses.Entity.Models.Nurse", "Nurse")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nurse");
                });

            modelBuilder.Entity("GaHealthcareNurses.Entity.Models.Job", b =>
                {
                    b.HasOne("GaHealthcareNurses.Entity.Models.Employer", "Employer")
                        .WithMany("Jobs")
                        .HasForeignKey("EmployerId");

                    b.Navigation("Employer");
                });

            modelBuilder.Entity("GaHealthcareNurses.Entity.Models.Nurse", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GaHealthcareNurses.Entity.Models.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId");

                    b.Navigation("IdentityUser");

                    b.Navigation("State");
                });

            modelBuilder.Entity("GaHealthcareNurses.Entity.Models.Reference", b =>
                {
                    b.HasOne("GaHealthcareNurses.Entity.Models.Nurse", "Nurse")
                        .WithMany("References")
                        .HasForeignKey("NurseId");

                    b.Navigation("Nurse");
                });

            modelBuilder.Entity("GaHealthcareNurses.Entity.Models.RequiredService", b =>
                {
                    b.HasOne("GaHealthcareNurses.Entity.Models.Client", "Client")
                        .WithMany("RequiredServices")
                        .HasForeignKey("ClientId");

                    b.HasOne("GaHealthcareNurses.Entity.Models.ServiceList", "ServiceList")
                        .WithMany("RequiredServices")
                        .HasForeignKey("ServiceListId");

                    b.Navigation("Client");

                    b.Navigation("ServiceList");
                });

            modelBuilder.Entity("GaHealthcareNurses.Entity.Models.State", b =>
                {
                    b.HasOne("GaHealthcareNurses.Entity.Models.Country", "Country")
                        .WithMany("States")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("GaHealthcareNurses.Entity.Models.TaskList", b =>
                {
                    b.HasOne("GaHealthcareNurses.Entity.Models.VisitNote", "VisitNote")
                        .WithMany("TaskLists")
                        .HasForeignKey("VisitNoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VisitNote");
                });

            modelBuilder.Entity("GaHealthcareNurses.Entity.Models.UploadDocuments", b =>
                {
                    b.HasOne("GaHealthcareNurses.Entity.Models.Nurse", "Nurse")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nurse");
                });

            modelBuilder.Entity("GaHealthcareNurses.Entity.Models.VisitNote", b =>
                {
                    b.HasOne("GaHealthcareNurses.Entity.Models.Employer", "Employer")
                        .WithMany("VisitNotes")
                        .HasForeignKey("EmployerId");

                    b.HasOne("GaHealthcareNurses.Entity.Models.Job", "Job")
                        .WithMany("VisitNotes")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GaHealthcareNurses.Entity.Models.Nurse", "Nurse")
                        .WithMany("VisitNotes")
                        .HasForeignKey("NurseId");

                    b.HasOne("GaHealthcareNurses.Entity.Models.Patient", "Patient")
                        .WithMany("VisitNotes")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employer");

                    b.Navigation("Job");

                    b.Navigation("Nurse");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("GaHealthcareNurses.Entity.Models.WorkExperience", b =>
                {
                    b.HasOne("GaHealthcareNurses.Entity.Models.Nurse", "Nurse")
                        .WithMany("WorkExperiences")
                        .HasForeignKey("NurseId");

                    b.Navigation("Nurse");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GaHealthcareNurses.Entity.Models.CareRecipientLocation", b =>
                {
                    b.Navigation("CareRecipients");
                });

            modelBuilder.Entity("GaHealthcareNurses.Entity.Models.CareRecipientRelationship", b =>
                {
                    b.Navigation("CareRecipients");

                    b.Navigation("Clients");
                });

            modelBuilder.Entity("GaHealthcareNurses.Entity.Models.City", b =>
                {
                    b.Navigation("CareRecipients");

                    b.Navigation("Clients");
                });

            modelBuilder.Entity("GaHealthcareNurses.Entity.Models.Client", b =>
                {
                    b.Navigation("CareRecipients");

                    b.Navigation("RequiredServices");
                });

            modelBuilder.Entity("GaHealthcareNurses.Entity.Models.Country", b =>
                {
                    b.Navigation("States");
                });

            modelBuilder.Entity("GaHealthcareNurses.Entity.Models.EducationType", b =>
                {
                    b.Navigation("Education");
                });

            modelBuilder.Entity("GaHealthcareNurses.Entity.Models.Employer", b =>
                {
                    b.Navigation("Jobs");

                    b.Navigation("VisitNotes");
                });

            modelBuilder.Entity("GaHealthcareNurses.Entity.Models.Job", b =>
                {
                    b.Navigation("VisitNotes");
                });

            modelBuilder.Entity("GaHealthcareNurses.Entity.Models.Nurse", b =>
                {
                    b.Navigation("Certifications");

                    b.Navigation("Educations");

                    b.Navigation("References");

                    b.Navigation("VisitNotes");

                    b.Navigation("WorkExperiences");
                });

            modelBuilder.Entity("GaHealthcareNurses.Entity.Models.Patient", b =>
                {
                    b.Navigation("CareCoordinationNotes");

                    b.Navigation("VisitNotes");
                });

            modelBuilder.Entity("GaHealthcareNurses.Entity.Models.ServiceList", b =>
                {
                    b.Navigation("RequiredServices");
                });

            modelBuilder.Entity("GaHealthcareNurses.Entity.Models.State", b =>
                {
                    b.Navigation("CareRecipients");

                    b.Navigation("Cities");

                    b.Navigation("Clients");
                });

            modelBuilder.Entity("GaHealthcareNurses.Entity.Models.VisitNote", b =>
                {
                    b.Navigation("TaskLists");
                });
#pragma warning restore 612, 618
        }
    }
}
