using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace GaHealthcareNurses.DbMigration.Migrations
{
    public partial class AddedCarePlanTable : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "CarePlan",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    JobId = table.Column<int>(type: "int", nullable: false),
                    NurseId = table.Column<string>(type: "nvarchar(450)", nullable: true),
                    EmployerId = table.Column<string>(type: "nvarchar(450)", nullable: true),
                    PatientClaimNo = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CareStartDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    CertificationFrom = table.Column<DateTime>(type: "datetime2", nullable: false),
                    CertificationTo = table.Column<DateTime>(type: "datetime2", nullable: false),
                    MedicalRecordNo = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ProviderNo = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    DiagnosisC = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Medicationsl = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    DmeSuppliesi = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SafetyMeasures = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ClinicianSignatureAndDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    HHAReceivedDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    PhysicianName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PhysicianAddress = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NutritionalRequirements = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Allergies = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FunctionalLimitations = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ActivitiesPermitted = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MentalStatus = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Prognosis = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Interventions = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Goals = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AdvanceDirectives = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    RehabPotential = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    DischargePlanning = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Frequencies = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    LocationName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    LocationNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CodeStatus = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CnaPlanOfCareAllergies = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Diagnosis = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Diet = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Alert = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsOrientedPerson = table.Column<bool>(type: "bit", nullable: false),
                    IsOrientedPlace = table.Column<bool>(type: "bit", nullable: false),
                    IsOrientedTime = table.Column<bool>(type: "bit", nullable: false),
                    IsOrientedConfused = table.Column<bool>(type: "bit", nullable: false),
                    IsDentures = table.Column<bool>(type: "bit", nullable: false),
                    IsDentureUpper = table.Column<bool>(type: "bit", nullable: false),
                    IsDentureLower = table.Column<bool>(type: "bit", nullable: false),
                    IsDenturePartial = table.Column<bool>(type: "bit", nullable: false),
                    IsBedBound = table.Column<bool>(type: "bit", nullable: false),
                    IsBedRestWithBrp = table.Column<bool>(type: "bit", nullable: false),
                    IsUpAsTolerated = table.Column<bool>(type: "bit", nullable: false),
                    IsHearingDeficit = table.Column<bool>(type: "bit", nullable: false),
                    IsHearingDeficitAid = table.Column<bool>(type: "bit", nullable: false),
                    HearingAid = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsHearingDeficitSpeech = table.Column<bool>(type: "bit", nullable: false),
                    IsVisualDeficit = table.Column<bool>(type: "bit", nullable: false),
                    IsVisualDeficitGlasses = table.Column<bool>(type: "bit", nullable: false),
                    IsVisualDeficitContacts = table.Column<bool>(type: "bit", nullable: false),
                    IsVisualDeficitOther = table.Column<bool>(type: "bit", nullable: false),
                    IsAssistiveDevices = table.Column<bool>(type: "bit", nullable: false),
                    IsObserveTemp = table.Column<bool>(type: "bit", nullable: false),
                    IsObserveTempOver = table.Column<bool>(type: "bit", nullable: false),
                    ObserveTempOver = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsObserveTempUnder = table.Column<bool>(type: "bit", nullable: false),
                    ObserveTempUnder = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsObservePulse = table.Column<bool>(type: "bit", nullable: false),
                    IsObservePulseOver = table.Column<bool>(type: "bit", nullable: false),
                    ObservePulseOver = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsObservePulseUnder = table.Column<bool>(type: "bit", nullable: false),
                    ObservePulseUnder = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsObserveBP = table.Column<bool>(type: "bit", nullable: false),
                    IsObserveBPOver = table.Column<bool>(type: "bit", nullable: false),
                    ObserveBPOver = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsObserveBPUnder = table.Column<bool>(type: "bit", nullable: false),
                    ObserveBPUnder = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsObserveIntake = table.Column<bool>(type: "bit", nullable: false),
                    IsObserveIntakeOver = table.Column<bool>(type: "bit", nullable: false),
                    ObserveIntakeOver = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsObserveIntakeUnder = table.Column<bool>(type: "bit", nullable: false),
                    ObserveIntakeUnder = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsObserveOutputAmount = table.Column<bool>(type: "bit", nullable: false),
                    IsObserveOutputAmountOver = table.Column<bool>(type: "bit", nullable: false),
                    ObserveOutputAmountOver = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsObserveOutputAmountUnder = table.Column<bool>(type: "bit", nullable: false),
                    ObserveOutputAmountUnder = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsObserveWeight = table.Column<bool>(type: "bit", nullable: false),
                    IsObserveWeightGain = table.Column<bool>(type: "bit", nullable: false),
                    IsObserveWeightLoss = table.Column<bool>(type: "bit", nullable: false),
                    ObserveWeightLoss = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsObserveOther1 = table.Column<bool>(type: "bit", nullable: false),
                    ObserveOther1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsObserveOther2 = table.Column<bool>(type: "bit", nullable: false),
                    ObserveOther2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsObserveNoBMInDays = table.Column<bool>(type: "bit", nullable: false),
                    IsObservePainAbove = table.Column<bool>(type: "bit", nullable: false),
                    ObservePainAbove = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsObserveChangesInSkin = table.Column<bool>(type: "bit", nullable: false),
                    ObserveChangesInSkin = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsObserveReddenedArea = table.Column<bool>(type: "bit", nullable: false),
                    IsObserveReddenedOther = table.Column<bool>(type: "bit", nullable: false),
                    ObserveReddenedOther = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsSafetyFallPrecautions = table.Column<bool>(type: "bit", nullable: false),
                    IsSafetyAmbulateOnly = table.Column<bool>(type: "bit", nullable: false),
                    IsSafetySideRailsUp = table.Column<bool>(type: "bit", nullable: false),
                    IsSafetySwallowing = table.Column<bool>(type: "bit", nullable: false),
                    IsSafetyHip = table.Column<bool>(type: "bit", nullable: false),
                    IsSafetySeizure = table.Column<bool>(type: "bit", nullable: false),
                    IsSafetyBleeding = table.Column<bool>(type: "bit", nullable: false),
                    IsSafetyProneToFractures = table.Column<bool>(type: "bit", nullable: false),
                    IsSafetyOther1 = table.Column<bool>(type: "bit", nullable: false),
                    SafetyOther1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsSafetyOther2 = table.Column<bool>(type: "bit", nullable: false),
                    SafetyOther2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsInstructionsAmputee = table.Column<bool>(type: "bit", nullable: false),
                    InstructionsAmputee = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsInstructionsSpecialEquip = table.Column<bool>(type: "bit", nullable: false),
                    InstructionsSpecialEquip = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsInstructionsOxygen = table.Column<bool>(type: "bit", nullable: false),
                    InstructionsOxygen = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsInstructionsWeight = table.Column<bool>(type: "bit", nullable: false),
                    InstructionsWeight = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsInstructionsOther = table.Column<bool>(type: "bit", nullable: false),
                    InstructionsOther = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsVitalSignsTemp = table.Column<bool>(type: "bit", nullable: false),
                    VitalSignsTempFrequency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    VitalSignsTempNotes = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsVitalSignsPulse = table.Column<bool>(type: "bit", nullable: false),
                    VitalSignsPulseFrequency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    VitalSignsPulseNotes = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsVitalSignsRespirations = table.Column<bool>(type: "bit", nullable: false),
                    VitalSignsRespirationsFrequency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    VitalSignsRespirationsNotes = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsVitalSignsBP = table.Column<bool>(type: "bit", nullable: false),
                    VitalSignsBPFrequency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    VitalSignsBPNotes = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsVitalSignsPainRating = table.Column<bool>(type: "bit", nullable: false),
                    VitalSignsPainRatingFrequency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    VitalSignsPainRatingNotes = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsVitalSignsWeight = table.Column<bool>(type: "bit", nullable: false),
                    VitalSignsWeightFrequency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    VitalSignsWeightNotes = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsVitalSignsIntake = table.Column<bool>(type: "bit", nullable: false),
                    VitalSignsIntakeFrequency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    VitalSignsIntakeNotes = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsVitalSignsOutput = table.Column<bool>(type: "bit", nullable: false),
                    VitalSignsOutputFrequency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    VitalSignsOutputNotes = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    VitalSignsOther = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsVitalSignsOther = table.Column<bool>(type: "bit", nullable: false),
                    VitalSignsOtherFrequency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    VitalSignsOtherNotes = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsEliminationLastBM = table.Column<bool>(type: "bit", nullable: false),
                    EliminationLastBMFrequency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EliminationLastBMNotes = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsEliminationAssistWithToilet = table.Column<bool>(type: "bit", nullable: false),
                    EliminationAssistWithToiletFrequency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EliminationAssistWithToiletNotes = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsEliminationBedPan = table.Column<bool>(type: "bit", nullable: false),
                    EliminationBedPanFrequency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EliminationBedPanNotes = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsEliminationCCare = table.Column<bool>(type: "bit", nullable: false),
                    EliminationCCareFrequency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EliminationCCareNotes = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsEliminationCCareExternal = table.Column<bool>(type: "bit", nullable: false),
                    IsEliminationCCareUrethral = table.Column<bool>(type: "bit", nullable: false),
                    IsEliminationCCareSuprapublic = table.Column<bool>(type: "bit", nullable: false),
                    IsEliminationUrineBag = table.Column<bool>(type: "bit", nullable: false),
                    EliminationUrineBagFrequency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EliminationUrineBagNotes = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsEliminationOstomy = table.Column<bool>(type: "bit", nullable: false),
                    EliminationOstomyFrequency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EliminationOstomyNotes = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EliminationOther1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsEliminationOther1 = table.Column<bool>(type: "bit", nullable: false),
                    EliminationOther1Frequency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EliminationOther1Notes = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EliminationOther2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsEliminationOther2 = table.Column<bool>(type: "bit", nullable: false),
                    EliminationOther2Frequency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EliminationOther2Notes = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsPersonalCare = table.Column<bool>(type: "bit", nullable: false),
                    IsPersonalCareBathChair = table.Column<bool>(type: "bit", nullable: false),
                    IsPersonalCareBathTub = table.Column<bool>(type: "bit", nullable: false),
                    IsPersonalCareBathBed = table.Column<bool>(type: "bit", nullable: false),
                    IsPersonalCareBathPartial = table.Column<bool>(type: "bit", nullable: false),
                    IsPersonalCareBathComplete = table.Column<bool>(type: "bit", nullable: false),
                    PersonalCareBathFrequency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PersonalCareBathNotes = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsPersonalCareShower = table.Column<bool>(type: "bit", nullable: false),
                    IsPersonalCareShowerUseChair = table.Column<bool>(type: "bit", nullable: false),
                    PersonalCareShowerFrequency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PersonalCareShowerNotes = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsPersonalCareOral = table.Column<bool>(type: "bit", nullable: false),
                    PersonalCareOralFrequency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PersonalCareOralNotes = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsPersonalCareSkinCare = table.Column<bool>(type: "bit", nullable: false),
                    IsPersonalCareSkinCareMoisturize = table.Column<bool>(type: "bit", nullable: false),
                    PersonalCareSkinCareFrequency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PersonalCareSkinCareNotes = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsPersonalCareCheckPressure = table.Column<bool>(type: "bit", nullable: false),
                    PersonalCareCheckPressureFrequency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PersonalCareCheckPressureNotes = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsPersonalCareHairCare = table.Column<bool>(type: "bit", nullable: false),
                    PersonalCareHairCareFrequency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PersonalCareHairCareNotes = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsPersonalCareShampoo = table.Column<bool>(type: "bit", nullable: false),
                    PersonalCareShampooFrequency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PersonalCareShampooNotes = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsPersonalCarePeriCare = table.Column<bool>(type: "bit", nullable: false),
                    PersonalCarePeriCareFrequency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PersonalCarePeriCareNotes = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsPersonalCareFootCare = table.Column<bool>(type: "bit", nullable: false),
                    PersonalCareFootCareFrequency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PersonalCareFootCareNotes = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsPersonalCareCleanNails = table.Column<bool>(type: "bit", nullable: false),
                    PersonalCareCleanNailsFrequency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PersonalCareCleanNailsNotes = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsPersonalCareDressing = table.Column<bool>(type: "bit", nullable: false),
                    PersonalCareDressingFrequency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PersonalCareDressingNotes = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsPersonalCareStockings = table.Column<bool>(type: "bit", nullable: false),
                    PersonalCareStockingsFrequency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PersonalCareStockingsNotes = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsPersonalCareShave = table.Column<bool>(type: "bit", nullable: false),
                    PersonalCareShaveFrequency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PersonalCareShaveNotes = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsPersonalCareOther1 = table.Column<bool>(type: "bit", nullable: false),
                    PersonalCareOther1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PersonalCareOther1Frequency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PersonalCareOther1Notes = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsPersonalCareOther2 = table.Column<bool>(type: "bit", nullable: false),
                    PersonalCareOther2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PersonalCareOther2Frequency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PersonalCareOther2Notes = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsNutritionPrepMeals = table.Column<bool>(type: "bit", nullable: false),
                    NutritionPrepMealsFrequency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NutritionPrepMealsNotes = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsNutritionPrepSnacks = table.Column<bool>(type: "bit", nullable: false),
                    NutritionPrepSnacksFrequency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NutritionPrepSnacksNotes = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsNutritionFeeding = table.Column<bool>(type: "bit", nullable: false),
                    NutritionFeedingFrequency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NutritionFeedingNotes = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsNutritionFluids = table.Column<bool>(type: "bit", nullable: false),
                    IsNutritionFluidsLimit = table.Column<bool>(type: "bit", nullable: false),
                    IsNutritionFluidsEncourage = table.Column<bool>(type: "bit", nullable: false),
                    NutritionFluidsFrequency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NutritionFluidsNotes = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsNutritionOther = table.Column<bool>(type: "bit", nullable: false),
                    NutritionOther = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NutritionOtherFrequency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NutritionOtherNotes = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsEnviromentalClean = table.Column<bool>(type: "bit", nullable: false),
                    IsEnviromentalCleanBathroom = table.Column<bool>(type: "bit", nullable: false),
                    IsEnviromentalCleanBedroom = table.Column<bool>(type: "bit", nullable: false),
                    IsEnviromentalCleanLiving = table.Column<bool>(type: "bit", nullable: false),
                    IsEnviromentalCleanKitchen = table.Column<bool>(type: "bit", nullable: false),
                    EnviromentalCleanFrequency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EnviromentalCleanNotes = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsEnviromentalLaundry = table.Column<bool>(type: "bit", nullable: false),
                    EnviromentalLaundryFrequency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EnviromentalLaundryNotes = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsEnvironmentalBedLinen = table.Column<bool>(type: "bit", nullable: false),
                    EnvironmentalBedLinenFrequency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EnvironmentalBedLinenNotes = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsEnvironmentalEquipCare = table.Column<bool>(type: "bit", nullable: false),
                    EnvironmentalEquipCareFrequency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EnvironmentalEquipCareNotes = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsEnvironmentalOther = table.Column<bool>(type: "bit", nullable: false),
                    EnvironmentalOther = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EnvironmentalOtherFrequency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    EnvironmentalOtherBotes = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsMedicationSelfAssist = table.Column<bool>(type: "bit", nullable: false),
                    MedicationSelfAssistFrequency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MedicationSelfAssistNotes = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsMedicationReminder = table.Column<bool>(type: "bit", nullable: false),
                    MedicationReminderFrequency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MedicationReminderNotes = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsActivityAmbulation = table.Column<bool>(type: "bit", nullable: false),
                    ActivityAmbulationFrequency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ActivityAmbulationNotes = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsActivityTransferAssist = table.Column<bool>(type: "bit", nullable: false),
                    IsActivityTransferAssistChair = table.Column<bool>(type: "bit", nullable: false),
                    IsActivityTransferAssistBed = table.Column<bool>(type: "bit", nullable: false),
                    IsActivityTransferAssistCommode = table.Column<bool>(type: "bit", nullable: false),
                    IsActivityTransferAssistShower = table.Column<bool>(type: "bit", nullable: false),
                    IsActivityTransferAssistTub = table.Column<bool>(type: "bit", nullable: false),
                    IsActivityTransferAssistHoyerLift = table.Column<bool>(type: "bit", nullable: false),
                    IsActivityExcercise = table.Column<bool>(type: "bit", nullable: false),
                    IsActivityExcercisePT = table.Column<bool>(type: "bit", nullable: false),
                    IsActivityExcerciseOT = table.Column<bool>(type: "bit", nullable: false),
                    IsActivityExcerciseSLP = table.Column<bool>(type: "bit", nullable: false),
                    ActivityExcerciseFrequency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ActivityExcerciseNotes = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsActivityReposition = table.Column<bool>(type: "bit", nullable: false),
                    ActivityRepositionFrequency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ActivityRepositionNotes = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsActivityROM = table.Column<bool>(type: "bit", nullable: false),
                    IsActivityROMActive = table.Column<bool>(type: "bit", nullable: false),
                    IsActivityROMPassive = table.Column<bool>(type: "bit", nullable: false),
                    IsActivityArmRight = table.Column<bool>(type: "bit", nullable: false),
                    IsActivityArmLeft = table.Column<bool>(type: "bit", nullable: false),
                    IsActivityLegRight = table.Column<bool>(type: "bit", nullable: false),
                    IsActivityLegLeft = table.Column<bool>(type: "bit", nullable: false),
                    ActivityROMFrequency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ActivityROMNotes = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsActivityOther1 = table.Column<bool>(type: "bit", nullable: false),
                    ActivityOther1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ActivityOther1Frequency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ActivityOther1Notes = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsActivityOther2 = table.Column<bool>(type: "bit", nullable: false),
                    ActivityOther2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ActivityOther2Frequency = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ActivityOther2Notes = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsAssistiveDevicesWC = table.Column<bool>(type: "bit", nullable: false),
                    IsAssistiveDevicesWalker = table.Column<bool>(type: "bit", nullable: false),
                    IsAssistiveDevicesCane = table.Column<bool>(type: "bit", nullable: false),
                    IsAssistiveDevicesCrutches = table.Column<bool>(type: "bit", nullable: false),
                    IsAssistiveDevicesBraceSplint = table.Column<bool>(type: "bit", nullable: false),
                    IsAssistiveDevicesOther = table.Column<bool>(type: "bit", nullable: false),
                    AssistiveDevicesOther = table.Column<string>(type: "nvarchar(max)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CarePlan", x => x.Id);
                    table.ForeignKey(
                        name: "FK_CarePlan_Employer_EmployerId",
                        column: x => x.EmployerId,
                        principalTable: "Employer",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_CarePlan_Job_JobId",
                        column: x => x.JobId,
                        principalTable: "Job",
                        principalColumn: "JobId",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_CarePlan_Nurse_NurseId",
                        column: x => x.NurseId,
                        principalTable: "Nurse",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "IX_CarePlan_EmployerId",
                table: "CarePlan",
                column: "EmployerId");

            migrationBuilder.CreateIndex(
                name: "IX_CarePlan_JobId",
                table: "CarePlan",
                column: "JobId");

            migrationBuilder.CreateIndex(
                name: "IX_CarePlan_NurseId",
                table: "CarePlan",
                column: "NurseId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "CarePlan");
        }
    }
}
