//using System.Net;
//using Microsoft.AspNetCore.Http;
//using System;
//using Microsoft.Extensions.Logging;
//using System.Threading.Tasks;
//using Newtonsoft.Json;
//using Microsoft.AspNetCore.Builder;
//using Microsoft.AspNetCore.Diagnostics;

//namespace BeequoServices.Extensions
//{
//    public static class ExceptionMiddlewareExtension
//    {
//        public static void ConfigureExceptionHandler(this IApplicationBuilder app, ILog logger)
//        {
//            app.UseExceptionHandler(appError =>
//            {
//                appError.Run(async context =>
//                {
//                    context.Response.StatusCode = (int)HttpStatusCode.InternalServerError;
//                    context.Response.ContentType = "application/json";

//                    var contextFeature = context.Features.Get<IExceptionHandlerFeature>();
//                    if (contextFeature != null)
//                    {
//                        logger.Error($"Something went wrong: {contextFeature.Error}");

//                        await context.Response.WriteAsync(new ErrorDetails()
//                        {
//                            StatusCode = context.Response.StatusCode,
//                            Message = "Internal Server Error. Error generated by NLog!"
//                        }.ToString());
//                    }
//                });
//            });
//        }
//    }
//}


