//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Services.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;&gt;
        ///    &lt;link href=&quot;https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;500;600;700&amp;display=swap&quot; rel=&quot;stylesheet&quot;&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            margin: 0;
        ///            padding: 0;
        ///            font-family: &apos;Montserrat&apos;, sans-serif;
        ///        }
        ///
        ///        * {
        ///            box-sizing: border-box;
        ///        }
        ///
        ///        .fieldset_box {
        ///           [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CarePlanPDF {
            get {
                return ResourceManager.GetString("CarePlanPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;&gt;
        ///    &lt;link href=&quot;https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;500;600;700&amp;display=swap&quot; rel=&quot;stylesheet&quot;&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            margin: 0;
        ///            padding: 0;
        ///            font-family: &apos;Montserrat&apos;, sans-serif;
        ///        }
        ///
        ///        * {
        ///            box-sizing: border-box;
        ///        }
        ///
        ///        .fieldset_box {
        ///           [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DischargeSummaryPDF {
            get {
                return ResourceManager.GetString("DischargeSummaryPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;&gt;
        ///    &lt;link href=&quot;https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;500;600;700&amp;display=swap&quot;
        ///          rel=&quot;stylesheet&quot;&gt;
        ///    &lt;style&gt;
        ///        * {
        ///            box-sizing: border-box;
        ///        }
        ///
        ///        body {
        ///            margin: 0;
        ///            padding: 0;
        ///            font-family: &apos;Montserrat&apos;, sans-serif;
        ///        }
        ///
        ///        .Service {
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ServiceAgreementPDF {
            get {
                return ResourceManager.GetString("ServiceAgreementPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;&gt;
        ///    &lt;link href=&quot;https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;500;600;700&amp;display=swap&quot;
        ///          rel=&quot;stylesheet&quot;&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            margin: 0;
        ///            padding: 0;
        ///            font-family: &apos;Montserrat&apos;, sans-serif;
        ///        }
        ///
        ///
        ///
        ///        .Service {
        ///            padding: 20px 5px 0;
        ///            max-width: 770p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SupervisoryVisitPDF {
            get {
                return ResourceManager.GetString("SupervisoryVisitPDF", resourceCulture);
            }
        }
    }
}
