using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text;

namespace GaHealthcareNurses.Entity.ViewModels
{
    public class AdultAssessmentRequestModel
    {
        public int AdultAssessmentId { get; set; }
        public int JobId { get; set; }
        public string NurseId { get; set; }
        public string EmployerId { get; set; }
        public DateTime? DateOfAssessment { get; set; }
        [Required]
        public string BillingCode { get; set; }
        public string TimeIn { get; set; }
        public string TimeOut { get; set; }
        public string LocationName { get; set; }
        public string LocationPhone { get; set; }
        [Required]
        public DateTime? StartOfCaredate { get; set; }
        [Required]
        public DateTime? CertificationFromDate { get; set; }
        [Required]
        public DateTime? CertificationToDate { get; set; }
        public bool IsAmericanIndian { get; set; }
        public bool IsAsian { get; set; }
        public bool IsBlackAmerican { get; set; }
        public bool IsHispanic { get; set; }
        public bool IsNativeHawaiian { get; set; }
        public bool IsWhite { get; set; }
        [Required]
        public string ReferringPhysician { get; set; }
        [Required]
        public string PhysicianAddress { get; set; }
        [Required]
        public string PhysicianPhone { get; set; }
        public string IsRecentHosp { get; set; }
        public DateTime? RecentHospDate1 { get; set; }
        public string RecentHospReason1 { get; set; }
        public DateTime? RecentHospDate2 { get; set; }
        public string RecentHospReason2 { get; set; }
        public DateTime? RecentHospDate3 { get; set; }
        public string RecentHospReason3 { get; set; }
        public DateTime? LastContactDate { get; set; }
        public string LastContactReason { get; set; }
        public bool IsPneumonia { get; set; }
        public string Pneumonia { get; set; }
        public DateTime? PneumoniaDate { get; set; }
        public string PneumoniaLocation { get; set; }
        public bool IsInfluenza { get; set; }
        public string Influenza { get; set; }
        public DateTime? InfluenzaDate { get; set; }
        public string InfluenzaLocation { get; set; }
        public bool IsShingle { get; set; }
        public string Shingle { get; set; }
        public DateTime? ShingleDate { get; set; }
        public string ShingleLocation { get; set; }
        public bool IsTetanus { get; set; }
        public string Tetanus { get; set; }
        public DateTime? TetanusDate { get; set; }
        public string TetanusLocation { get; set; }
        public string ReasonForHomecare { get; set; }
        public string IsAwareAdvanceDirective { get; set; }
        public string IsADCopiesAtHome { get; set; }
        public string IsADCopiesOther { get; set; }
        public string ADCopiesOther { get; set; }
        public string ADLabel1 { get; set; }
        public string ADDescription1 { get; set; }
        public DateTime? ADEffectiveDate1 { get; set; }
        public string ADLabel2 { get; set; }
        public string ADDescription2 { get; set; }
        public DateTime? ADEffectiveDate2 { get; set; }
        public string ADLabel3 { get; set; }
        public string ADDescription3 { get; set; }
        public DateTime? ADEffectiveDate3 { get; set; }
        public string MaritalStatus { get; set; }
        public string PatientLivesIn { get; set; }
        public string FacilityName { get; set; }
        public string PatientLives { get; set; }
        public string WithOthers { get; set; }
        public string FamilyCareGiverSupport { get; set; }
        public string PatientHandlingFinances { get; set; }
        public bool IsSituationImpactingPlan { get; set; }
        public string SituationImpactingPlan { get; set; }
        public string EmergencyContactName { get; set; }
        public string EmergencyContactPhone { get; set; }
        public string LivingArrangementComments { get; set; }
        public bool IsWithCareGiver { get; set; }
        public string PrimaryCGName { get; set; }
        public string PrimaryCGPhone { get; set; }
        public string PrimaryCGAddress { get; set; }
        public string PrimaryCGRelationship { get; set; }
        public string PrimaryCGLanguage { get; set; }
        public bool IsPCGAssistFinincially { get; set; }
        public bool IsPCGAssistShopping { get; set; }
        public bool IsPCGAssistHomeMtce { get; set; }
        public bool IsPCGAssistADLs { get; set; }
        public bool IsPCGAssistMedication { get; set; }
        public bool IsPCGAssistOther { get; set; }
        public string PCGAssistOther { get; set; }
        public string PCGAvailability { get; set; }
        public string AdditionalCareGivers { get; set; }
        public bool IsPatientWithRepresentative { get; set; }
        public string RepresentativeName { get; set; }
        public string RepresentativePhone { get; set; }
        public string RepresentativeAddress { get; set; }
        public string RepresentativeRelationship { get; set; }
        public string RepresentativeType { get; set; }
        public string RepresentativeRole { get; set; }
        public string RepresentativeLanguage { get; set; }
        public string AdditionalRepresentative { get; set; }
        public bool IsAdequateHeating { get; set; }
        public bool IsAdequateWater { get; set; }
        public bool IsAdequateSanitation { get; set; }
        public bool IsAdequateLighting { get; set; }
        public bool IsAdequateFoodStorage { get; set; }
        public bool IsAdequateMedication { get; set; }
        public bool IsEnvironmentCluttered { get; set; }
        public bool IsFloorCoveringUnsecured { get; set; }
        public bool IsStairsSafe { get; set; }
        public bool IsPetsKept { get; set; }
        public bool IsStairsIntoHome { get; set; }
        public bool IsStairsNextToPatientAreas { get; set; }
        public bool IsOxygenInUse { get; set; }
        public bool IsBathroomAccessible { get; set; }
        public bool IsBathroomWithoutGrabBars { get; set; }
        public bool IsElectricCordsFrayed { get; set; }
        public bool IsInsectRodentInfested { get; set; }
        public bool IsUnableToUsePhone { get; set; }
        public bool IsSmokeDetectorsMissing { get; set; }
        public bool IsNoneIdentified { get; set; }
        public string IsFireExtinguisherPresent { get; set; }
        public string IsSomkeDetectorOnAllLevels { get; set; }
        public string IsSmokeDetectorMaintained { get; set; }
        public string IsMoreThanOneExit { get; set; }
        public string IsTherePlanForExit { get; set; }
        public string IsTherePlanForPowerFailure { get; set; }
        public string IsTherePlanForNaturalDisaster { get; set; }
        public string IsOxygenSignPosted { get; set; }
        public string IsPlanForBackupOxygen { get; set; }
        public bool IsSafetyPlanDiscussed { get; set; }
        public string SafetyPlanDiscussed { get; set; }
        public DateTime? ClearPathwaysDate { get; set; }
        public DateTime? EquipmentSafetyDate { get; set; }
        public DateTime? FalPrecautionDate { get; set; }
        public DateTime? AssistiveDeviceDate { get; set; }
        public bool IsWheelChairInHome { get; set; }
        public bool IsWalkerInHome { get; set; }
        public bool IsCommodeInHome { get; set; }
        public bool IsShowerBenchInHome { get; set; }
        public bool IsCaneInHome { get; set; }
        public bool IsOtherEquipmentInHome { get; set; }
        public string OtherEquipment { get; set; }
        public bool IsNoEquipmentInHome { get; set; }
        public string IsPatientAbleToUseSafely { get; set; }
        public string SafetyMeasuresRecommended { get; set; }
        public string Pulse { get; set; }
        public string PulseSite { get; set; }
        public string BloodPressure { get; set; }
        public string BloodPressurePosition { get; set; }
        public string BPMeasuredOnLeft { get; set; }
        public string Temperature { get; set; }
        public string TemperatureMethod { get; set; }
        public string TemperatureUnit { get; set; }
        public string Respirations { get; set; }
        public string RespirationsType { get; set; }
        public string BloodSugar { get; set; }
        public string BloodSugarMeasuresAs { get; set; }
        public string PatientSelfMonitoring { get; set; }
        public bool IsPatientSelfMonitoringTemp { get; set; }
        public bool IsPatientSelfMonitoringPulse { get; set; }
        public bool IsPatientSelfMonitoringBP { get; set; }
        public bool IsPatientSelfMonitoringSP02 { get; set; }
        public string Weight { get; set; }
        public string WeightUnit { get; set; }
        public string WeightMeasuredAs { get; set; }
        public string WeightStatus { get; set; }
        public string Height { get; set; }
        public string HeightMeasuredAs { get; set; }
        public string SP02Sat { get; set; }
        public string PTInr { get; set; }
        public string PtInrIsVenipuncture { get; set; }
        public string AdditionalVitalSigns { get; set; }
        public bool IsVisionGlasses { get; set; }
        public bool IsVisionGlaucoma { get; set; }
        public bool IsVisionGlaucomaR { get; set; }
        public bool IsVisionGlaucomaL { get; set; }
        public bool IsVisionMacularDegen { get; set; }
        public bool IsVisionMacularDegenR { get; set; }
        public bool IsVisionMacularDegenL { get; set; }
        public bool IsVisionLegallyBlind { get; set; }
        public bool IsVisionLegallyBlindR { get; set; }
        public bool IsVisionLegallyBlindL { get; set; }
        public bool IsVisionOther { get; set; }
        public string VisionOther { get; set; }
        public bool IsVisionContacts { get; set; }
        public bool IsVisionContactsR { get; set; }
        public bool IsVisionContactsL { get; set; }
        public bool IsVisionCataracts { get; set; }
        public bool IsVisionCataractsR { get; set; }
        public bool IsVisionCataractsL { get; set; }
        public bool IsVisionBlurred { get; set; }
        public bool IsVisionBlurredR { get; set; }
        public bool IsVisionBlurredL { get; set; }
        public bool IsVisionNoDeficits { get; set; }
        public bool IsENTMHearingLoss { get; set; }
        public bool IsENTMHearingLossR { get; set; }
        public bool IsENTMHearingLossL { get; set; }
        public bool IsENTMHearingAids { get; set; }
        public bool IsENTMHearingAidsR { get; set; }
        public bool IsENTMHearingAidsL { get; set; }
        public bool IsENTMEarPain { get; set; }
        public bool IsENTMEarPainR { get; set; }
        public bool IsENTMEarPainL { get; set; }
        public bool IsENTMNasalCongestion { get; set; }
        public bool IsENTMChewingProblems { get; set; }
        public bool IsENTMTinnitus { get; set; }
        public bool IsENTMLossOfSmell { get; set; }
        public bool IsENTMHoarseness { get; set; }
        public bool IsENTMSoreThroat { get; set; }
        public bool IsENTMDentures { get; set; }
        public bool IsENTMDenturesUppper { get; set; }
        public bool IsENTMDenturesLower { get; set; }
        public bool IsENTMDenturesPartial { get; set; }
        public bool IsENTMNoDeficits { get; set; }
        public bool IsENTMOther { get; set; }
        public string ENTMOther { get; set; }
        public string VisionComments { get; set; }
        public string EarNoseThroatMouthComments { get; set; }
        public bool IsNoPain { get; set; }
        public bool IsPainScaleFaces { get; set; }
        public bool IsPainScaleNumeric { get; set; }
        public bool IsPainScaleOther { get; set; }
        public string PainScaleOther { get; set; }
        public string PainLocation { get; set; }
        public string CauseOfPain { get; set; }
        public bool IsPainSharp { get; set; }
        public bool IsPainDull { get; set; }
        public bool IsPainCramping { get; set; }
        public bool IsPainAching { get; set; }
        public bool IsPainTingling { get; set; }
        public bool IsPainThrobbing { get; set; }
        public bool IsPainShooting { get; set; }
        public bool IsPainPinching { get; set; }
        public bool IsPainBurning { get; set; }
        public bool IsPainWorseByMovement { get; set; }
        public bool IsPainWorseByTimeOfDay { get; set; }
        public bool IsPainWorseByPosture { get; set; }
        public bool IsPainWorseByOther { get; set; }
        public string PainWorseByOther { get; set; }
        public bool IsPainRelievedByMedication { get; set; }
        public bool IsPainRelievedByHeat { get; set; }
        public bool IsPainRelievedByIce { get; set; }
        public bool IsPainRelievedByRest { get; set; }
        public bool IsPainRelievedByRelaxation { get; set; }
        public bool IsPainRelievedByOther { get; set; }
        public string PainRelievedByOther { get; set; }
        public string FrequencyOfPainAndImpact { get; set; }
        public bool IsMedicationNeededNever { get; set; }
        public bool IsMedicationNeededLessThanDaily { get; set; }
        public bool IsMedicationNeeded2or3TimesDaily { get; set; }
        public bool IsMedicationNeededMoreThan3times { get; set; }
        public bool IsCurrentPainControlAdequate { get; set; }
        public bool IsMedicationNeededOther { get; set; }
        public string MedicationNeededOther { get; set; }
        public bool IsPatientUnabletoCommunicate { get; set; }
        public bool IsPatientDiaphoresis { get; set; }
        public bool IsPatientGrimacing { get; set; }
        public bool IsPatientMoaning { get; set; }
        public bool IsPatientGuarding { get; set; }
        public bool IsPatientIrritable { get; set; }
        public bool IsPaatientAngry { get; set; }
        public bool IsPatientTense { get; set; }
        public bool IsPatientRestless { get; set; }
        public bool IsPatientWithVitalSignsChange { get; set; }
        public bool IsPatientOther { get; set; }
        public string PatientOther { get; set; }
        public string WongBakerScale { get; set; }
        public string PainComments { get; set; }
        public bool IsIntegumentaryColor { get; set; }
        public string IntegumentaryColor { get; set; }
        public bool IsIntegumentaryColorOther { get; set; }
        public string IntegumentaryColorOther { get; set; }
        public bool IsIntegumentarySkin { get; set; }
        public string IntegumentarySkin { get; set; }
        public bool IsIntegumentaryTemp { get; set; }
        public bool IsIntegumentaryTempDry { get; set; }
        public bool IsIntegumentaryTempWarm { get; set; }
        public bool IsIntegumentaryTempCool { get; set; }
        public bool IsIntegumentaryTempClammy { get; set; }
        public bool IsIntegumentaryTempDiaphoretic { get; set; }
        public string SurgicalWound { get; set; }
        public string IntegumentaryLocation { get; set; }
        public bool IsIncisionClosedWithStaples { get; set; }
        public bool IsIncisionClosedWithSutures { get; set; }
        public bool IsIncisionClosedWithSteriStrips { get; set; }
        public bool IsIncisionClosedWithSurgicalAdhesive { get; set; }
        public bool IsIncisionClosedWithOther { get; set; }
        public string IncisionClosedWithOther { get; set; }
        public string IncisionSizeAndAppearance { get; set; }
        public bool IsWoundIdentified { get; set; }
        public bool BSSensoryPerceptionIs1 { get; set; }
        public bool BSSensoryPerceptionIs2 { get; set; }
        public bool BSSensoryPerceptionIs3 { get; set; }
        public bool BSSensoryPerceptionIs4 { get; set; }
        public string BSSensoryPerceptionScore { get; set; }
        public bool BSMoistureIs1 { get; set; }
        public bool BSMoistureIs2 { get; set; }
        public bool BSMoistureIs3 { get; set; }
        public bool BSMoistureIs4 { get; set; }
        public string BSMoistureScore { get; set; }
        public bool BSActivityIs1 { get; set; }
        public bool BSActivityIs2 { get; set; }
        public bool BSActivityIs3 { get; set; }
        public bool BSActivityIs4 { get; set; }
        public string BSActivityScore { get; set; }
        public bool BSMobilityIs1 { get; set; }
        public bool BSMobilityIs2 { get; set; }
        public bool BSMobilityIs3 { get; set; }
        public bool BSMobilityIs4 { get; set; }
        public string BSMobilityScore { get; set; }
        public bool BSNutritionIs1 { get; set; }
        public bool BSNutritionIs2 { get; set; }
        public bool BSNutritionIs3 { get; set; }
        public bool BSNutritionIs4 { get; set; }
        public string BSNutritionScore { get; set; }
        public bool BSFrictionAndShearIs1 { get; set; }
        public bool BSFrictionAndShearIs2 { get; set; }
        public bool BSFrictionAndShearIs3 { get; set; }
        public string BSFrictionAndShearScore { get; set; }
        public bool HasHistoryOfAsthma { get; set; }
        public bool HasHistoryOfMildAsthma { get; set; }
        public bool HasHistoryOfModerateAsthma { get; set; }
        public bool HasHistoryOfSevereAsthma { get; set; }
        public bool HasHistoryOfIntermittentAsthma { get; set; }
        public bool HasHistoryOfPersistentAsthma { get; set; }
        public bool HasHistoryOfExacerbatedAsthma { get; set; }
        public bool HasHistoryOfEmphysema { get; set; }
        public bool HasHistoryOfBronchitis { get; set; }
        public bool HasHistoryOfCOPD { get; set; }
        public bool HasHistoryOfTB { get; set; }
        public bool HasHistoryOfPleurisy { get; set; }
        public bool HasHistoryOfPneumonia { get; set; }
        public bool HasHistoryOfSmoking { get; set; }
        public string HistoryOfSmoking { get; set; }
        public bool HasHistoryOfNonSmoker { get; set; }
        public bool HasHistoryOfHeartFailure { get; set; }
        public bool HasHistoryOfAngina { get; set; }
        public bool HasHistoryOfBradycardia { get; set; }
        public bool HasHistoryOfHyportension { get; set; }
        public bool HasHistoryOfHypertension { get; set; }
        public bool HasHistoryOfAtrialFib { get; set; }
        public bool HasHistoryOfPacemaker { get; set; }
        public bool HasHistoryOfTachycardia { get; set; }
        public bool HasHistoryOfImplantedDefribilator { get; set; }
        public bool HasHistoryOfStent { get; set; }
        public string StentLocation { get; set; }
        public bool HasHistoryOfPad { get; set; }
        public bool HasHistoryOfPalpitations { get; set; }
        public bool HasNoHistory { get; set; }
        public bool IsBreathsoundsClear { get; set; }
        public bool IsClearRUpper { get; set; }
        public bool IsClearRLower { get; set; }
        public bool IsClearLUpper { get; set; }
        public bool IsClearLLower { get; set; }
        public bool IsDiminishedRUpper { get; set; }
        public bool IsDiminishedRLower { get; set; }
        public bool IsDiminishedLUpper { get; set; }
        public bool IsDiminishedLLower { get; set; }
        public bool IsAbsentRUpper { get; set; }
        public bool IsAbsentRLower { get; set; }
        public bool IsAbsentLUpper { get; set; }
        public bool IsAbsentLLower { get; set; }
        public bool IsCracklesRUpper { get; set; }
        public bool IsCracklesRLower { get; set; }
        public bool IsCracklesLUpper { get; set; }
        public bool IsCracklesLLower { get; set; }
        public bool IsWheezingRUpper { get; set; }
        public bool IsWheezingRLower { get; set; }
        public bool IsWheezingLUpper { get; set; }
        public bool IsWheezingLLower { get; set; }
        public bool IsRespirationsEasy { get; set; }
        public bool IsOrthopnea { get; set; }
        public bool IsHemoptysis { get; set; }
        public bool IsCyanosis { get; set; }
        public bool IsDyspnea { get; set; }
        public bool IsSputum { get; set; }
        public string SputumColor { get; set; }
        public bool IsCough { get; set; }
        public bool IsCoughProductive { get; set; }
        public bool IsCoughDry { get; set; }
        public bool IsCoughChronic { get; set; }
        public bool IsCoughAcute { get; set; }
        public bool IsO2 { get; set; }
        public string O2LperMin { get; set; }
        public bool IsViaMask { get; set; }
        public bool IsViaNC { get; set; }
        public bool IsViaPRN { get; set; }
        public bool IsViaContinous { get; set; }
        public bool IsViaCPAC { get; set; }
        public bool IsTracheostomy { get; set; }
        public string Tracheostomy { get; set; }
        public bool IsBreathSoundsOther { get; set; }
        public string BreathSoundsOther { get; set; }
        public bool IsNormalHeartSounds { get; set; }
        public bool IsAbnormalHeartSounds { get; set; }
        public bool IsChestPain { get; set; }
        public bool IsVertigo { get; set; }
        public bool IsNeckVein { get; set; }
        public bool IsDiaphoresis { get; set; }
        public bool IsFatigues { get; set; }
        public bool IsArrhythmia { get; set; }
        public bool IsCapillary { get; set; }
        public string Capillary { get; set; }
        public bool IsCompression { get; set; }
        public bool IsPedalPulses { get; set; }
        public bool IsPedalR { get; set; }
        public bool IsPedalL { get; set; }
        public bool IsEdema { get; set; }
        public bool IsEdemaPedal { get; set; }
        public bool IsEdemaR { get; set; }
        public bool IsEdemaL { get; set; }
        public bool IsEdemaDependent { get; set; }
        public bool IsRightAnkle { get; set; }
        public string RightAnkle { get; set; }
        public bool IsRightCalf { get; set; }
        public string RightCalf { get; set; }
        public bool IsLeftAnkle { get; set; }
        public string LeftAnkle { get; set; }
        public bool IsLeftCalf { get; set; }
        public string LeftCalf { get; set; }
        public bool IsHistoryOther { get; set; }
        public string HistoryOther { get; set; }
        public string HistoryCommentery { get; set; }
        public bool IsFrequent { get; set; }
        public bool IsChronic { get; set; }
        public bool IsKidneyStones { get; set; }
        public bool IsRenalDisease { get; set; }
        public bool IsPolycysticDisease { get; set; }
        public bool IsGenitourinaryNoHistory { get; set; }
        public bool IsGenitourinaryOther { get; set; }
        public string GenitourinaryOther { get; set; }
        public bool IsFrequency { get; set; }
        public bool IsUrgency { get; set; }
        public bool IsIncontinence { get; set; }
        public bool IsAnuria { get; set; }
        public bool IsActiveUTI { get; set; }
        public bool IsFoulOdor { get; set; }
        public bool IsBurning { get; set; }
        public bool IsPain { get; set; }
        public bool IsColor { get; set; }
        public bool IsColorClear { get; set; }
        public bool IsColorCloudy { get; set; }
        public bool IsColorYellow { get; set; }
        public bool IsColorDarkYellow { get; set; }
        public bool IsColorBrown { get; set; }
        public bool IsColorRedPink { get; set; }
        public bool IsDialysis { get; set; }
        public string DialysisTypeFreq { get; set; }
        public bool IsDialysisOther { get; set; }
        public string DialysisOther { get; set; }
        public bool IsVoidingWithoutProblems { get; set; }
        public bool IsCatheter { get; set; }
        public string Catheter { get; set; }
        public bool IsFoleySize { get; set; }
        public string FoleySize { get; set; }
        public bool IsIrrigationCatheter { get; set; }
        public bool IsSelfCatheter { get; set; }
        public bool IsCatheterOther { get; set; }
        public string CatheterOther { get; set; }
        public string CatheterLastPerformedBy { get; set; }
        public string CatheterComments { get; set; }
        public bool HasHistoryOfHeartBurn { get; set; }
        public bool HasHistoryOfUIsers { get; set; }
        public bool HasHistoryOfGIBleed { get; set; }
        public bool HasHistoryOfGERD { get; set; }
        public bool HasHistoryOfCrohnsDisease { get; set; }
        public bool HasNoHistoryOfGastro { get; set; }
        public bool HasHistoryOfOtherGastro { get; set; }
        public string HistoryOfOtherGastro { get; set; }
        public string LastBM { get; set; }
        public bool IsBMConsistencySoft { get; set; }
        public bool IsBMConsistencyFormed { get; set; }
        public bool IsBMConsistencyHard { get; set; }
        public bool IsBMConsistencyMucous { get; set; }
        public bool IsBMConsistencyOther { get; set; }
        public string BMConsistencyOther { get; set; }
        public bool IsBowelSoundNormal { get; set; }
        public bool IsBowelSoundHyperActive { get; set; }
        public bool IsBowelSoundDiminished { get; set; }
        public bool IsBowelSoundAbsent { get; set; }
        public bool IsAbdominalPain { get; set; }
        public bool IsAbdominalDistention { get; set; }
        public bool IsConstipation { get; set; }
        public bool IsDiarrhea { get; set; }
        public bool IsLastBmIncontinence { get; set; }
        public bool IsAbdGirth { get; set; }
        public string AbdGirth { get; set; }
        public bool IsIndigestion { get; set; }
        public bool IsNausea { get; set; }
        public bool IsVomiting { get; set; }
        public bool IsEnteralFeeding { get; set; }
        public string EnteralFeeding { get; set; }
        public bool IsPlacement { get; set; }
        public bool IsResidualAmount { get; set; }
        public string ResidualAmount { get; set; }
        public bool IsOstomy { get; set; }
        public string Ostomy { get; set; }
        public bool IsColostomy { get; set; }
        public bool IsIleostomy { get; set; }
        public bool Urostomy { get; set; }
        public bool IsLastOther { get; set; }
        public string LastOther { get; set; }
        public bool IsStoma { get; set; }
        public bool IsPink { get; set; }
        public bool IsRed { get; set; }
        public bool IsMoist { get; set; }
        public bool IsSelfCare { get; set; }
        public bool IsNeedsAssistance { get; set; }
        public string Appetite { get; set; }
        public bool IsDifficultySwallowing { get; set; }
        public bool IsNSIllnessOrCondition { get; set; }
        public bool IsNSEatsFewer { get; set; }
        public bool IsNSEatsFewFruits { get; set; }
        public bool IsNSDrinks { get; set; }
        public bool IsNSHasToothProblems { get; set; }
        public bool IsNSDoesntHaveEnoughMoney { get; set; }
        public bool IsNSEatsAlone { get; set; }
        public bool IsNSTakesThree { get; set; }
        public bool IsNSLostOrGainedPounds { get; set; }
        public bool IsNSNotAlwaysAble { get; set; }
        public string NutritionalScreeningTotal { get; set; }
        public string NSComments { get; set; }
        public bool IsDiabetes { get; set; }
        public string Diabetes { get; set; }
        public bool IsAbleToDrawInsulin { get; set; }
        public string WhoAsssistsToDraw { get; set; }
        public string AssistPatient { get; set; }
        public bool IsAbleToAdministerInsulin { get; set; }
        public string WhoAssistsToAdminister { get; set; }
        public string WhoAssistPatient { get; set; }
        public bool IsUrineTestingPerformed { get; set; }
        public bool IsBloodSugarGlucometer { get; set; }
        public string GlucometerType { get; set; }
        public bool IsHowOftenChecked { get; set; }
        public string HowOftenChecked { get; set; }
        public bool IsDiabeticFootInspection { get; set; }
        public string DiabeticFootInspectionFindings { get; set; }
        public bool IsThyroidDisease { get; set; }
        public string ThyroidDisease { get; set; }
        public bool IsHyperProcedure { get; set; }
        public DateTime? HyperProcedureDate { get; set; }
        public bool IsHypoOnSupplementalTreatment { get; set; }
        public string HypoOnSupplementalTreatment { get; set; }
        public string NutritionalRequirements { get; set; }
        public bool IsInfusionNA { get; set; }
        public bool IsInfusionAntibiotics { get; set; }
        public bool IsInfusionPainControl { get; set; }
        public bool IsPeripheralLine { get; set; }
        public bool IsMidlineCatheter { get; set; }
        public bool IsCentralLine { get; set; }
        public bool IsInfusionOther { get; set; }
        public string InfusionOther { get; set; }
        public string InfusionTypeBrand { get; set; }
        public bool IsTypeGroshong { get; set; }
        public bool IsTypeNonGroshong { get; set; }
        public bool IsTypeTunneled { get; set; }
        public bool IsTypeNonTunneled { get; set; }
        public bool IsTypePICC { get; set; }
        public bool IsTypeInfusionPort { get; set; }
        public bool IsTypeOther { get; set; }
        public string TypeOther { get; set; }
        public string InsertionSite { get; set; }
        public DateTime? InsertionDate { get; set; }
        [Required]
        public string Lumen { get; set; }
        public bool IsMidArmCircumference { get; set; }
        public string MidArmCircumference { get; set; }
        public string Inches { get; set; }
        public bool IsExternalCathLength { get; set; }
        public bool IsDressingChange { get; set; }
        public string DressingChange { get; set; }
        public bool IsCapChange { get; set; }
        public string CapChange { get; set; }
        public bool IsCatheterFlush { get; set; }
        public string CatheterFlush { get; set; }
        public bool IsTubingChange { get; set; }
        public string TubingChange { get; set; }
        public bool IsInfusionTherapy { get; set; }
        public string InfusionTherapy { get; set; }
        public bool IsInfusionTherapyAdmin { get; set; }
        public string InfusionTherapyAdmin { get; set; }
        public bool IsAdministrationDetails { get; set; }
        public string AdministrationDetails { get; set; }
        public bool IsLabsDrawn { get; set; }
        public string LabsDrawn { get; set; }
        public bool IsOtherDetails { get; set; }
        public string OtherDetails { get; set; }
        public bool IsSeeInfusionAddendum { get; set; }
        public bool IsHistoryOfDementia { get; set; }
        public bool IsHistoryOfParkinsons { get; set; }
        public bool IsHistoryOfMS { get; set; }
        public bool IsHistoryOfMemoryLoss { get; set; }
        public bool IsHistoryOfSeizures { get; set; }
        public bool IsHistoryOfTIA { get; set; }
        public bool IsTraumaticBrainInjury { get; set; }
        public string TraumaticBrainInjury { get; set; }
        public bool IsPsychiatricIllness { get; set; }
        public string PsychiatricIllness { get; set; }
        public bool IsStroke { get; set; }
        public string StrokeDeficits { get; set; }
        public string StrokeDeficitsSpecified { get; set; }
        public bool IsOtherNeuro { get; set; }
        public string OtherNeuro { get; set; }
        public bool IsNoNeuroHistory { get; set; }
        public bool IsNeuroOriented { get; set; }
        public bool IsNeuroPerson { get; set; }
        public bool IsNeuroPlace { get; set; }
        public bool IsNeuroTime { get; set; }
        public bool IsNeuroAlert { get; set; }
        public bool IsNeuroDisoriented { get; set; }
        public bool IsNeuroConfused { get; set; }
        public bool IsNeuroAgitated { get; set; }
        public bool IsNeuroDepressed { get; set; }
        public bool IsNeuroOther { get; set; }
        public string NeuroOther { get; set; }
        public bool IsPupillaryReaction { get; set; }
        public bool IsPupillaryReactionR { get; set; }
        public bool IsPupillaryReactionL { get; set; }
        public bool IsLossOfBalance { get; set; }
        public bool IsDizzy { get; set; }
        public bool IsSpasms { get; set; }
        public bool IsForgetful { get; set; }
        public bool IsSeizuresTremors { get; set; }
        public bool IsSlurredSpeech { get; set; }
        public bool IsChangeInCognition { get; set; }
        public bool IsNumbnesTingling { get; set; }
        public bool IsFacialDroop { get; set; }
        public bool IsSpeechDifficulties { get; set; }
        public bool IsChangeInMood { get; set; }
        public string ChangeInMood { get; set; }
        public bool IsHeadache { get; set; }
        public string HeadacheFrequencyDuration { get; set; }
        public bool IsWeaknessParalysis { get; set; }
        public bool IsWeaknessParalysisR { get; set; }
        public bool IsWeaknessParalysisL { get; set; }
        public string IsNeuroLocation { get; set; }
        public bool IsGripStrengthStrong { get; set; }
        public bool IsGripStrengthWeak { get; set; }
        public bool IsGripStrengthEqual { get; set; }
        public bool IsGripStrengthUnequal { get; set; }
        public string GripStrengthUnequal { get; set; }
        public bool IsGripStrengthOther { get; set; }
        public string GripStrengthOther { get; set; }
        public bool IsNoDeficits { get; set; }
        public string InfusionNeuroComments { get; set; }
        public bool IsProInterpreter { get; set; }
        public bool IsProInterpreterAccepted { get; set; }
        public bool IsProInterpreterDeclinedUseOwn { get; set; }
        public string ProInterpreterDeclinedUseOwn { get; set; }
        public bool IsProInterpreterDeclined { get; set; }
        public string ProInterpreterDeclined { get; set; }
        public bool IsLBLanguage { get; set; }
        public bool IsLBReadingWriting { get; set; }
        public bool IsLBMental { get; set; }
        public bool IsLBFunctional { get; set; }
        public bool IsLBPsychosocial { get; set; }
        public bool IsLBPhysical { get; set; }
        public bool IsLBHearing { get; set; }
        public bool IsLBVision { get; set; }
        public bool IsLBOther { get; set; }
        public string LBOther { get; set; }
        public bool IsLBNoneIdentified { get; set; }
        public bool IsSleepRestAdequate { get; set; }
        public bool IsSleepRestInadequate { get; set; }
        public string SleepRestInadequate { get; set; }
        public bool IsSpiritualCulturalImplication { get; set; }
        public string SpiritualCulturalImplication { get; set; }
        public bool IsSpiritualResource { get; set; }
        public string SpiritualResource { get; set; }
        public bool IsAlcoholOrDrugAddictionNone { get; set; }
        public bool IsAlcoholOrDrugAddictionUnknown { get; set; }
        public bool IsAlcoholOrDrugAddictionSuspected { get; set; }
        public string AlcoholOrDrugAddictionSuspected { get; set; }
        public bool IsMentalNodeficits { get; set; }
        public bool Evidenceobserved { get; set; }
        public bool EvidenceActual { get; set; }
        public bool EvidencePotential { get; set; }
        public bool EvidenceEmotiona { get; set; }
        public bool EvidencePhysical { get; set; }
        public bool EvidenceFinancial { get; set; }
        public string DescribeReported { get; set; }
        public bool IsPatientReadyToLearn { get; set; }
        public bool IsPatientHavingDifficultyCoping { get; set; }
        public bool IsPatientWithdrawn { get; set; }
        public bool IsPatientAngry { get; set; }
        public bool IsPatientDiscouraged { get; set; }
        public bool IsPatientUnmotivated { get; set; }
        public bool IsPatientOthers { get; set; }
        public string PatientOthers { get; set; }
        public bool IsCareGiverReadyToLearn { get; set; }
        public bool IsCareGiverHavingDifficultyCoping { get; set; }
        public bool IsCareGiverAngry { get; set; }
        public bool IsCareGiverWithdrawn { get; set; }
        public bool IsCareGiverDiscouraged { get; set; }
        public bool IsCareGiverUnmotivated { get; set; }
        public bool IsCareGiverOther { get; set; }
        public string CareGiverOther { get; set; }
        public string MentalComments { get; set; }
        public bool IsAbuseNoneObservedReported { get; set; }
        public string MentalPsychosocialCognitiveStatus { get; set; }
        public bool HasHistoryOfArthritis { get; set; }
        public bool HasHistoryOfOsteoporosis { get; set; }
        public bool HasHistoryOfOsteoarthritis { get; set; }
        public bool HasHistoryOfOsteoarthritisPrimary { get; set; }
        public bool HasHistoryOfOsteoarthritisSecondary { get; set; }
        public bool HasHistoryOfBursitis { get; set; }
        public bool HasHistoryOfTendinitis { get; set; }
        public bool HasHistoryOfMuscularDystrophy { get; set; }
        public bool HasHistoryOfLupus { get; set; }
        public bool HasHistoryOfContractures { get; set; }
        public bool HasHistoryOfRotatorCuffTear { get; set; }
        public bool HasHistoryOfRotatorCuffTearR { get; set; }
        public bool HasHistoryOfRotatorCuffTearL { get; set; }
        public bool HasHistoryOfMyastheniaGravis { get; set; }
        public bool HasNoMusculoskeletalHistory { get; set; }
        public bool IsAbnormalGait { get; set; }
        public string AbnormalGait { get; set; }
        public bool IsLimitedROM { get; set; }
        public string LimitedROMlocation { get; set; }
        public bool IsLimitedMobility { get; set; }
        public string LimitedMobility { get; set; }
        public bool IsWeightBearingLimitations { get; set; }
        public string WeightBearingLimitations { get; set; }
        public bool IsAmputation { get; set; }
        public bool IsAmputationBK { get; set; }
        public bool IsAmputationAK { get; set; }
        public bool IsAmputationUE { get; set; }
        public bool IsAmputationR { get; set; }
        public bool IsAmputationL { get; set; }
        public bool IsAmputationOther { get; set; }
        public string AmputationOther { get; set; }
        public bool IsProsthesisAppliance { get; set; }
        public string ProsthesisApplianceSpecified { get; set; }
        public string ActivityEatingAL { get; set; }
        public string ActivityTransferAL { get; set; }
        public string ActivityDressingAL { get; set; }
        public string ActivityBathingAL { get; set; }
        public string ActivityToiletingAL { get; set; }
        public string ActivityAmbulationAL { get; set; }
        public string ActivityMealPrepAL { get; set; }
        public string ActivityHousekeepingAL { get; set; }
        public string ActivityDailyLivingComment { get; set; }
        public bool IsFRAbove65 { get; set; }
        public bool IsFRDx { get; set; }
        public bool IsFRPriorFall { get; set; }
        public bool IsFRIncontinence { get; set; }
        public bool IsFRVisualImpairment { get; set; }
        public bool IsFRImpairedFunction { get; set; }
        public bool IsFREnvironmentalHaz { get; set; }
        public bool IsFRPolyPharmacy { get; set; }
        public bool IsFRPainAffecting { get; set; }
        public bool IsFRCognitiveImpairment { get; set; }
        public string MostRecentFall { get; set; }
        public string RecentFallAndOutcome { get; set; }
        public string RecentFallComments { get; set; }
        public string FunctionalLimitations { get; set; }
        public string ActivitiesPermitted { get; set; }
        public string HasPatientAllMedications { get; set; }
        public string HasPatientAllMedicationsNo { get; set; }
        public string IsMedicationManaged { get; set; }
        public string IsObstaclesWithNew { get; set; }
        public string ObstaclesWithNew { get; set; }
        public bool IsMedicationStorage { get; set; }
        public bool IsMedicationDisposal { get; set; }
        public bool IsMedicationExpiration { get; set; }
        public bool IsMedicationClearlyLabelled { get; set; }
        public bool IsMedicationOther { get; set; }
        public string MedicationOther { get; set; }
        public bool IsPillBoxUtilized { get; set; }
        public string PillBoxUtilized { get; set; }
        public bool IsNoMedications { get; set; }
        public string MedicationComments { get; set; }
        public bool HasHadHospitalAmission { get; set; }
        public bool HasPrimaryDagnosis { get; set; }
        public bool HasNeedsAssistanceWithADL { get; set; }
        public bool Has10OrMoreMedications { get; set; }
        public bool HasNeedsAssistanceWithMedication { get; set; }
        public bool HasNeedsAssistanceWithRespiratory { get; set; }
        public bool HasHadHosiptalAdmission { get; set; }
        public bool HasLearningBarrier { get; set; }
        public bool IsLeavingAlone { get; set; }
        public bool HasHadAFall { get; set; }
        public bool HasHadSkinUlcer { get; set; }
        public string AssessmentSummary { get; set; }
        public string SuppliesIssued { get; set; }
        public string InterventionsEducation { get; set; }
        public string ResponseToInterventions { get; set; }
        public bool IsRightsAndResponsibilities { get; set; }
        public bool IsDoNotResuscitate { get; set; }
        public bool IsHIPAANoticeOfPrivacy { get; set; }
        public bool IsEmergencyPlanning { get; set; }
        public bool IsWhenToContactPhysician { get; set; }
        public bool IsStandardPrecautions { get; set; }
        public bool IsMedicationRegimen { get; set; }
        public int IsStateHotlineNumber { get; set; }
        public bool IsAdvanceDirectives { get; set; }
        public bool IsOASISPrivacyNotice { get; set; }
        public bool IsAgencyPhone { get; set; }
        public bool IsDiseaseInfo { get; set; }
        public bool IsBasicHomeSafety { get; set; }
        public bool IsMaterialOthers { get; set; }
        public string MaterialOthers { get; set; }
        public string FrequencySN { get; set; }
        public string FrequencyOT { get; set; }
        public string FrequencyPT { get; set; }
        public string FrequencyST { get; set; }
        public string FrequencyMSW { get; set; }
        public string FrequencyHHA { get; set; }
        public string FrequencyRD { get; set; }
        public string FrequencyOther { get; set; }
        public string FrequencyEligibility { get; set; }
        public string FrequencyPrognosis { get; set; }
        public string FrequencyRehabPotential { get; set; }
        public string FrequencyDMESupplies { get; set; }
        public string FrequencyInterventions { get; set; }
        public string FrequencyGoals { get; set; }
        public bool IsCarePlanningPatient { get; set; }
        public bool IsCarePlanPhysician { get; set; }
        public bool IsCarePlanCaseManager { get; set; }
        public bool IsCarePlanClinicalManager { get; set; }
        public bool IsCarePlanSN { get; set; }
        public bool IsCarePlanPT { get; set; }
        public bool IsCarePlanPTA { get; set; }
        public bool IsCarePlanOT { get; set; }
        public bool IsCarePlanCOTA { get; set; }
        public bool IsCarePlanST { get; set; }
        public bool IsCarePlanAide { get; set; }
        public bool IsCarePlanMSW { get; set; }
        public bool IsCarePlanOther { get; set; }
        public string CarePlanOther { get; set; }
        public string CoordinationDetails { get; set; }
        public bool IsDischargePlanEstablished { get; set; }
        public string DischargePlanning { get; set; }
        public bool IsPlansForAssessment { get; set; }
        public bool IsPlansForTeaching { get; set; }
        public bool IsPlansForTreatment { get; set; }
        public bool IsPlansForPreparation { get; set; }
        public bool IsPlansForOther { get; set; }
        public string PlansForOther { get; set; }
        public string NextPhysicianVisitDate { get; set; }
        public string ReasonForVisit { get; set; }
        public string NameOfPhysician { get; set; }
        public string VerbalOrderFrom { get; set; }
        public DateTime? VerbalOrderReceivedDate { get; set; }
        public string VerbalOrderReceivedTime { get; set; }
        public string PhysicianAddressCity { get; set; }
        public string PhysicianAddressState { get; set; }
        public string PhysicianAddressZipCode { get; set; }
        public string PhysicianAddressPhone { get; set; }
        public List<WoundViewModel> Wound { get; set; }
        public List<DiagnosisViewModel> Diagnosis { get; set; } 
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public int Age { get; set; }
    }
}
