using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text;

namespace GaHealthcareNurses.Entity.ViewModels
{
    public class CarePlanRequestModel
    {
        public int Id { get; set; }
        public int JobId { get; set; }
        public string EmployerId { get; set; }
        public string NurseId { get; set; }
        [Required(ErrorMessage = "Please enter the Patient's HI Claim No")]
        public string PatientClaimNo { get; set; }
        [Required(ErrorMessage = "Start date is required")]
        public DateTime? CareStartDate { get; set; }
        [Required(ErrorMessage = "Certification period Start date is required")]
        public DateTime? CertificationFrom { get; set; }
        [Required(ErrorMessage = "Certification period End date is required")]
        public DateTime? CertificationTo { get; set; }
        [Required(ErrorMessage = "Please enter the Medical Record No")]
        public string MedicalRecordNo { get; set; }
        [Required(ErrorMessage = "Please enter the Provider No")]
        public string ProviderNo { get; set; }
        public string Eligibility { get; set; }
        public string DiagnosisC { get; set; }
        public string Medicationsl { get; set; }
        public string DmeSuppliesi { get; set; }
        public string SafetyMeasures { get; set; }
        public DateTime? VerbalSOCDate { get; set; }
        public DateTime? HHAReceivedDate { get; set; }
        public string PhysicianName { get; set; }
        public string PhysicianAddress { get; set; }
        public string NutritionalRequirements { get; set; }
        public string Allergies { get; set; }
        public string FunctionalLimitations { get; set; }
        public string ActivitiesPermitted { get; set; }
        public string MentalStatus { get; set; }
        public string Prognosis { get; set; }
        public string Interventions { get; set; }
        public string Goals { get; set; }
        public string AdvanceDirectives { get; set; }
        public string RehabPotential { get; set; }
        public string DischargePlanning { get; set; }
        public string Frequencies { get; set; }
        [Required(ErrorMessage = "Please enter the Location Name")]
        public string LocationName { get; set; }
        [Required(ErrorMessage = "Please enter the Location Number")]
        public string LocationNumber { get; set; }
        public string CodeStatus { get; set; }
        public string CnaPlanOfCareAllergies { get; set; }
        public string Diagnosis { get; set; }
        public string Diet { get; set; }
        public bool IsAlert { get; set; }
        public bool IsOrientedPerson { get; set; }
        public bool IsOrientedPlace { get; set; }
        public bool IsOrientedTime { get; set; }
        public bool IsOrientedConfused { get; set; }
        public bool IsDentures { get; set; }
        public bool IsDentureUpper { get; set; }
        public bool IsDentureLower { get; set; }
        public bool IsDenturePartial { get; set; }
        public bool IsBedBound { get; set; }
        public bool IsBedRestWithBrp { get; set; }
        public bool IsUpAsTolerated { get; set; }
        public bool IsHearingDeficit { get; set; }
        public bool IsHearingDeficitAid { get; set; }
        public string HearingAid { get; set; }
        public bool IsHearingDeficitSpeech { get; set; }
        public bool IsVisualDeficit { get; set; }
        public bool IsVisualDeficitGlasses { get; set; }
        public bool IsVisualDeficitContacts { get; set; }
        public bool IsVisualDeficitOther { get; set; }
        public bool IsAssistiveDevices { get; set; }
        public bool IsPertientInformationOther { get; set; }
        public string PertientInformationOther { get; set; }
        public bool IsObserveTemp { get; set; }
        public bool IsObserveTempOver { get; set; }
        public string ObserveTempOver { get; set; }
        public bool IsObserveTempUnder { get; set; }
        public string ObserveTempUnder { get; set; }
        public bool IsObservePulse { get; set; }
        public bool IsObservePulseOver { get; set; }
        public string ObservePulseOver { get; set; }
        public bool IsObservePulseUnder { get; set; }
        public string ObservePulseUnder { get; set; }
        public bool IsObserveRespiration { get; set; }
        public bool IsObserveRespirationOver { get; set; }
        public string ObserveRespirationOver { get; set; }
        public bool IsObserveRespirationUnder { get; set; }
        public string ObserveRespirationUnder { get; set; }
        public bool IsObserveBP { get; set; }
        public bool IsObserveBPOver { get; set; }
        public string ObserveBPOver { get; set; }
        public bool IsObserveBPUnder { get; set; }
        public string ObserveBPUnder { get; set; }
        public bool IsObserveIntake { get; set; }
        public bool IsObserveIntakeOver { get; set; }
        public string ObserveIntakeOver { get; set; }
        public bool IsObserveIntakeUnder { get; set; }
        public string ObserveIntakeUnder { get; set; }
        public bool IsObserveOutputAmount { get; set; }
        public bool IsObserveOutputAmountOver { get; set; }
        public string ObserveOutputAmountOver { get; set; }
        public bool IsObserveOutputAmountUnder { get; set; }
        public string ObserveOutputAmountUnder { get; set; }
        public bool IsObserveWeight { get; set; }
        public bool IsObserveWeightGain { get; set; }
        public bool IsObserveWeightLoss { get; set; }
        public string ObserveWeightLoss { get; set; }
        public bool IsObserveOther1 { get; set; }
        public string ObserveOther1 { get; set; }
        public bool IsObserveOther2 { get; set; }
        public string ObserveOther2 { get; set; }
        public bool IsObserveNoBMInDays { get; set; }
        public bool IsObservePainAbove { get; set; }
        public string ObservePainAbove { get; set; }
        public bool IsObserveChangesInSkin { get; set; }
        public string ObserveChangesInSkin { get; set; }
        public bool IsObserveReddenedArea { get; set; }
        public bool IsObserveReddenedOther { get; set; }
        public string ObserveReddenedOther { get; set; }
        public bool IsSafetyFallPrecautions { get; set; }
        public bool IsSafetyAmbulateOnly { get; set; }
        public bool IsSafetySideRailsUp { get; set; }
        public bool IsSafetySwallowing { get; set; }
        public bool IsSafetyHip { get; set; }
        public bool IsSafetySeizure { get; set; }
        public bool IsSafetyBleeding { get; set; }
        public bool IsSafetyProneToFractures { get; set; }
        public bool IsSafetyOther1 { get; set; }
        public string SafetyOther1 { get; set; }
        public bool IsSafetyOther2 { get; set; }
        public string SafetyOther2 { get; set; }
        public bool IsInstructionsAmputee { get; set; }
        public string InstructionsAmputee { get; set; }
        public bool IsInstructionsSpecialEquip { get; set; }
        public string InstructionsSpecialEquip { get; set; }
        public bool IsInstructionsOxygen { get; set; }
        public string InstructionsOxygen { get; set; }
        public bool IsInstructionsWeight { get; set; }
        public string InstructionsWeight { get; set; }
        public bool IsInstructionsOther { get; set; }
        public string InstructionsOther { get; set; }
        public bool IsVitalSignsTemp { get; set; }
        public string VitalSignsTempFrequency { get; set; }
        public string VitalSignsTempNotes { get; set; }
        public bool IsVitalSignsPulse { get; set; }
        public string VitalSignsPulseFrequency { get; set; }
        public string VitalSignsPulseNotes { get; set; }
        public bool IsVitalSignsRespirations { get; set; }
        public string VitalSignsRespirationsFrequency { get; set; }
        public string VitalSignsRespirationsNotes { get; set; }
        public bool IsVitalSignsBP { get; set; }
        public string VitalSignsBPFrequency { get; set; }
        public string VitalSignsBPNotes { get; set; }
        public bool IsVitalSignsPainRating { get; set; }
        public string VitalSignsPainRatingFrequency { get; set; }
        public string VitalSignsPainRatingNotes { get; set; }
        public bool IsVitalSignsWeight { get; set; }
        public string VitalSignsWeightFrequency { get; set; }
        public string VitalSignsWeightNotes { get; set; }
        public bool IsVitalSignsIntake { get; set; }
        public string VitalSignsIntakeFrequency { get; set; }
        public string VitalSignsIntakeNotes { get; set; }
        public bool IsVitalSignsOutput { get; set; }
        public string VitalSignsOutputFrequency { get; set; }
        public string VitalSignsOutputNotes { get; set; }
        public string VitalSignsOther { get; set; }
        public bool IsVitalSignsOther { get; set; }
        public string VitalSignsOtherFrequency { get; set; }
        public string VitalSignsOtherNotes { get; set; }
        public bool IsEliminationLastBM { get; set; }
        public string EliminationLastBMFrequency { get; set; }
        public string EliminationLastBMNotes { get; set; }
        public bool IsEliminationAssistWithToilet { get; set; }
        public string EliminationAssistWithToiletFrequency { get; set; }
        public string EliminationAssistWithToiletNotes { get; set; }
        public bool IsEliminationBedPan { get; set; }
        public string EliminationBedPanFrequency { get; set; }
        public string EliminationBedPanNotes { get; set; }
        public bool IsEliminationCCare { get; set; }
        public string EliminationCCareFrequency { get; set; }
        public string EliminationCCareNotes { get; set; }
        public bool IsEliminationCCareExternal { get; set; }
        public bool IsEliminationCCareUrethral { get; set; }
        public bool IsEliminationCCareSuprapublic { get; set; }
        public bool IsEliminationUrineBag { get; set; }
        public string EliminationUrineBagFrequency { get; set; }
        public string EliminationUrineBagNotes { get; set; }
        public bool IsEliminationOstomy { get; set; }
        public string EliminationOstomyFrequency { get; set; }
        public string EliminationOstomyNotes { get; set; }
        public string EliminationOther1 { get; set; }
        public bool IsEliminationOther1 { get; set; }
        public string EliminationOther1Frequency { get; set; }
        public string EliminationOther1Notes { get; set; }
        public string EliminationOther2 { get; set; }
        public bool IsEliminationOther2 { get; set; }
        public string EliminationOther2Frequency { get; set; }
        public string EliminationOther2Notes { get; set; }
        public bool IsPersonalCare { get; set; }
        public bool IsPersonalCareBathChair { get; set; }
        public bool IsPersonalCareBathTub { get; set; }
        public bool IsPersonalCareBathBed { get; set; }
        public string IsPersonalCareBathPartial { get; set; }
        public string PersonalCareBathFrequency { get; set; }
        public string PersonalCareBathNotes { get; set; }
        public bool IsPersonalCareShower { get; set; }
        public bool IsPersonalCareShowerUseChair { get; set; }
        public string PersonalCareShowerFrequency { get; set; }
        public string PersonalCareShowerNotes { get; set; }
        public bool IsPersonalCareOral { get; set; }
        public string PersonalCareOralFrequency { get; set; }
        public string PersonalCareOralNotes { get; set; }
        public bool IsPersonalCareSkinCare { get; set; }
        public bool IsPersonalCareSkinCareMoisturize { get; set; }
        public string PersonalCareSkinCareFrequency { get; set; }
        public string PersonalCareSkinCareNotes { get; set; }
        public bool IsPersonalCareCheckPressure { get; set; }
        public string PersonalCareCheckPressureFrequency { get; set; }
        public string PersonalCareCheckPressureNotes { get; set; }
        public bool IsPersonalCareHairCare { get; set; }
        public string PersonalCareHairCareFrequency { get; set; }
        public string PersonalCareHairCareNotes { get; set; }
        public bool IsPersonalCareShampoo { get; set; }
        public string PersonalCareShampooFrequency { get; set; }
        public string PersonalCareShampooNotes { get; set; }
        public bool IsPersonalCarePeriCare { get; set; }
        public string PersonalCarePeriCareFrequency { get; set; }
        public string PersonalCarePeriCareNotes { get; set; }
        public bool IsPersonalCareFootCare { get; set; }
        public string PersonalCareFootCareFrequency { get; set; }
        public string PersonalCareFootCareNotes { get; set; }
        public bool IsPersonalCareCleanNails { get; set; }
        public string PersonalCareCleanNailsFrequency { get; set; }
        public string PersonalCareCleanNailsNotes { get; set; }
        public bool IsPersonalCareDressing { get; set; }
        public string PersonalCareDressingFrequency { get; set; }
        public string PersonalCareDressingNotes { get; set; }
        public bool IsPersonalCareStockings { get; set; }
        public string PersonalCareStockingsFrequency { get; set; }
        public string PersonalCareStockingsNotes { get; set; }
        public bool IsPersonalCareShave { get; set; }
        public string PersonalCareShaveFrequency { get; set; }
        public string PersonalCareShaveNotes { get; set; }
        public bool IsPersonalCareOther1 { get; set; }
        public string PersonalCareOther1 { get; set; }
        public string PersonalCareOther1Frequency { get; set; }
        public string PersonalCareOther1Notes { get; set; }
        public bool IsPersonalCareOther2 { get; set; }
        public string PersonalCareOther2 { get; set; }
        public string PersonalCareOther2Frequency { get; set; }
        public string PersonalCareOther2Notes { get; set; }
        public bool IsNutritionPrepMeals { get; set; }
        public string NutritionPrepMealsFrequency { get; set; }
        public string NutritionPrepMealsNotes { get; set; }
        public bool IsNutritionPrepSnacks { get; set; }
        public string NutritionPrepSnacksFrequency { get; set; }
        public string NutritionPrepSnacksNotes { get; set; }
        public bool IsNutritionFeeding { get; set; }
        public string NutritionFeedingFrequency { get; set; }
        public string NutritionFeedingNotes { get; set; }
        public bool IsNutritionFluids { get; set; }
        public bool IsNutritionFluidsLimit { get; set; }
        public bool IsNutritionFluidsEncourage { get; set; }
        public string NutritionFluidsFrequency { get; set; }
        public string NutritionFluidsNotes { get; set; }
        public bool IsNutritionOther { get; set; }
        public string NutritionOther { get; set; }
        public string NutritionOtherFrequency { get; set; }
        public string NutritionOtherNotes { get; set; }
        public bool IsEnviromentalClean { get; set; }
        public bool IsEnviromentalCleanBathroom { get; set; }
        public bool IsEnviromentalCleanBedroom { get; set; }
        public bool IsEnviromentalCleanLiving { get; set; }
        public bool IsEnviromentalCleanKitchen { get; set; }
        public string EnviromentalCleanFrequency { get; set; }
        public string EnviromentalCleanNotes { get; set; }
        public bool IsEnviromentalLaundry { get; set; }
        public string EnviromentalLaundryFrequency { get; set; }
        public string EnviromentalLaundryNotes { get; set; }
        public bool IsEnvironmentalBedLinen { get; set; }
        public string EnvironmentalBedLinenFrequency { get; set; }
        public string EnvironmentalBedLinenNotes { get; set; }
        public bool IsEnvironmentalEquipCare { get; set; }
        public string EnvironmentalEquipCareFrequency { get; set; }
        public string EnvironmentalEquipCareNotes { get; set; }
        public bool IsEnvironmentalOther { get; set; }
        public string EnvironmentalOther { get; set; }
        public string EnvironmentalOtherFrequency { get; set; }
        public string EnvironmentalOtherNotes { get; set; }
        public bool IsMedicationSelfAssist { get; set; }
        public string MedicationSelfAssistFrequency { get; set; }
        public string MedicationSelfAssistNotes { get; set; }
        public bool IsMedicationReminder { get; set; }
        public string MedicationReminderFrequency { get; set; }
        public string MedicationReminderNotes { get; set; }
        public bool IsActivityAmbulation { get; set; }
        public string ActivityAmbulationFrequency { get; set; }
        public string ActivityAmbulationNotes { get; set; }
        public bool IsActivityTransferAssist { get; set; }
        public bool IsActivityTransferAssistChair { get; set; }
        public bool IsActivityTransferAssistBed { get; set; }
        public bool IsActivityTransferAssistCommode { get; set; }
        public bool IsActivityTransferAssistShower { get; set; }
        public bool IsActivityTransferAssistTub { get; set; }
        public bool IsActivityTransferAssistHoyerLift { get; set; }
        public string ActivityTransferAssistFrequency { get; set; }
        public string ActivityTransferAssistNotes { get; set; }
        public bool IsActivityExcercise { get; set; }
        public bool IsActivityExcercisePT { get; set; }
        public bool IsActivityExcerciseOT { get; set; }
        public bool IsActivityExcerciseSLP { get; set; }
        public string ActivityExcerciseFrequency { get; set; }
        public string ActivityExcerciseNotes { get; set; }
        public bool IsActivityReposition { get; set; }
        public string ActivityRepositionFrequency { get; set; }
        public string ActivityRepositionNotes { get; set; }
        public bool IsActivityROM { get; set; }
        public bool IsActivityROMActive { get; set; }
        public bool IsActivityROMPassive { get; set; }
        public bool IsActivityArmRight { get; set; }
        public bool IsActivityArmLeft { get; set; }
        public bool IsActivityLegRight { get; set; }
        public bool IsActivityLegLeft { get; set; }
        public string ActivityROMFrequency { get; set; }
        public string ActivityROMNotes { get; set; }
        public bool IsActivityOther1 { get; set; }
        public string ActivityOther1 { get; set; }
        public string ActivityOther1Frequency { get; set; }
        public string ActivityOther1Notes { get; set; }
        public bool IsActivityOther2 { get; set; }
        public string ActivityOther2 { get; set; }
        public string ActivityOther2Frequency { get; set; }
        public string ActivityOther2Notes { get; set; }
        public bool IsAssistiveDevicesWC { get; set; }
        public bool IsAssistiveDevicesWalker { get; set; }
        public bool IsAssistiveDevicesCane { get; set; }
        public bool IsAssistiveDevicesCrutches { get; set; }
        public bool IsAssistiveDevicesBraceSplint { get; set; }
        public bool IsAssistiveDevicesOther { get; set; }
        public string AssistiveDevicesOther { get; set; }
        public DateTime EntryDate { get; set; }
        public string PatientName { get; set; }
        public string PatientAddress { get; set; }
        public int PatientAge { get; set; }
        public string PatientGender { get; set; }
        public string AgencyName { get; set; }
        public string AgencyAddress { get; set; }
    }
    public class CarePlanPDFBytes
    {
        public byte[] Bytes { get; set; }
    }
}
